oasis-drivers-cpp: Fix build error due to QA issue
Error was:

  ERROR: oasis-drivers-cpp-git-r0 do_package_qa: QA Issue: oasis-drivers-cpp rdepends on oasis-msgs-dev [dev-deps]
  ERROR: oasis-drivers-cpp-git-r0 do_package_qa: Fatal QA errors were found, failing task.